### PR TITLE
Modified Example Notebooks with new ori file

### PR DESCRIPTION
**Pull request by ckarwin**
I updated the spectral fit example notebooks (crab, GRB, and extended) with the new ori file, in order to be compatible with the recent changes to the SpacecraftFile class. The new ori file is the DC2 ori file which also includes the orbital information. It can be found here: https://s3.us-west-1.wasabisys.com/cosi-pipeline-public/COSI-SMEX/DC2/Data/Orientation/20280301_3_month_with_orbital_info.ori.  

I also needed to update COSILike, since the scattmap now requires passing the source location. Lastly, I added an option in the scattmap calculation (and COSILike) to include the Earth occultation, with the default set to true. 

This PR resolves issues #260 #262 and partially #263 (the other notebooks will also need to be updated, which I leave to the respective owners).

### CODE REVIEW

**Comment by ckarwin** [comment]
@hirokiyoneda This is ready for review when you have time.

**Comment by ckarwin** [comment]
@hirokiyoneda Ok, I needed to update the unit test coverage for additional lines I added, but all tests are now passing. 

@eneights I recently merged your PR #256, but then soon realized it wasn't in the right place. It was in a directory called "spectral_fits", but it's better to be in the threeml directory, since that is the class it is testing. I moved it to the right place as part of this PR, and so there is nothing for you to do, but please be aware.

**Comment by hiyoneda** [comment]
I am running the notebooks, and found a quick mistake. The 3rd cell in `SpectralFit_Crab.ipynb' is:
```
fetch_wasabi_file('COSI-SMEX/DC2/Data/Orientation/20280301_3_month_with_orbital_info.ori', output=str(data_path / '20280301_3_month_modified.ori'))
```
Should it be data_path / '20280301_3_month_with_orbital_info.ori'?

**Comment by ckarwin** [comment]
@hiyoneda Yes, sorry, it's fixed now.

**Comment by hiyoneda** [comment]
I confirmed that the new orientation file worked well without any errors, but I encountered the following error on the GRB notebook. I think that the binned event file is in the old format and does not have `coordsys` in `PsiChi` axis. Do you think that it is easy to fix it? (If not, I can merge this PR and make a new issue).

Screenshot 2024-11-14 at 12 43 26

**Comment by ckarwin** [comment]
@hiyoneda Thanks for double checking. I ran through all three notebooks before making a PR to make sure everything was working, including the GRB notebook, and I didn't have this same issue. As part of this I downloaded all the files from scratch using the fetch_wasabi commands in the notebook. I just ran the GRB notebook again and it works fine for me. Can you double check that you are using the correct files and that they were downloaded ok?

**Review by hiyoneda — APPROVED** [review]
I used old files I previously downloaded, sorry. After downloading the new ones, everything worked well. Now we can merge this!

**Comment by ckarwin** [comment]
Ok, no problem. Thanks again.

**Pull request merged**
