### PR TITLE
Cleanup and tests

### LINKED ISSUE #170: Fix data IO test. inputs_crab.yaml no longer exists
screenshot_2024-03-18_at_14 55 12

### PR DESCRIPTION
**Pull request by israelmcmc**
I'm reorganizing the cosipy module in preparation for the unit tests. Each module will have at least a test.

Work done so far:
- Removed cosipy/coordinates. That code is now in [mhealpy](https://gitlab.com/burstcube/mhealpy) or [scoords](https://github.com/cositools/scoords)
- Removed cosipy/config. That code is now in [yayc](https://github.com/cositools/yayc)
    - Added yayc to the dependencies, and changed the import where appropriate (DataIO and  imaging modules)
- Moved cosipy_makeplots to DataIO (only module using it)
- Fix existing unit tests
    - The response module test was failing because the config file now uses the astromodels format for source specification
    - (IMC: actually still failing, but for another reason. Investigating.) The Data IO module was failing because it was missing the corresponding test data. I added a subset (621 event) of GalacticScan.inc1.id1.crab2hr.extracted(_.testsample._)tra.gz and inputs_crab.yaml

Fixes #170

### CODE REVIEW

**Comment by israelmcmc** [comment]
@ckarwin Yes, good catch. I fixed it by using tempfile to create a system temporary folder that is automatically removed at the end of the tests. Since I was at it, I added a few test cases to have full coverage for that file.

However, due to what it seems an unrelated issue, the automatic pipelines are not failing. I think it has to do with new releases of some dependencies. I'll look into it, but they are passing on my machine.

**Comment by ckarwin** [comment]
@israelmcmc Yeah, everything is still passing on my machine as well, after pulling your latest commit.

**Review by Yong2Sheng — APPROVED** [review]
It looks good to me.

**Comment by ckarwin** [comment]
@Yong2Sheng @israelmcmc Thanks, Yong, for approving the PR. So can it be merged soon, or still waiting on something? I see there is still a problem with some of the unit tests.

**Comment by israelmcmc** [comment]
Thanks @Yong2Sheng and @ckarwin. I'd like to have the test passing before merging. I think it's a problem with the dependencies, maybe I just need to specify the versions. I'll work on it.

**Comment by ckarwin** [comment]
Thanks @israelmcmc! Yeah, it would be helpful to have it merged whenever you can, to make it easier for adding more tests.

**Comment by israelmcmc** [comment]
In the meantime, people can branch off my branch (israelmcmc:cleanup_and_tests) instead of develop, and everything else is the same. But yet, I agree it's easier and better to just merge it, I'll get to it

**Comment by Yong2Sheng** [comment]
Hi @israelmcmc, do you mean to fork and make PR to your branch (`israelmcmc:cleanup_and_test`)? Thanks!

**Comment by israelmcmc** [comment]
@Yong2Sheng Kind off. Yes to making a new branch from my branch, but you don't need to fork my repo and you can open the PR directly to develop on this repo.

**Comment by ckarwin** [comment]
@israelmcmc I tested the error in the checks as follows:

1. I Copied your cleanup and tests branch into my forked repo. 
2. I Made a PR #185, to replicate the error that you get. 
3. Indeed, I get the same errors related to matplotlib.cm, relating to the discussion in issue #180. 
4. I then updated `install_requires` in setup.py file with 'matplotlib<=3.8.3'. After doing this all checks passed. 

So I think if you do the same in your setup file it should fix the issue. Can you try?

**Comment by ckarwin** [comment]
@israelmcmc Actually, I just made a PR into your branch with the update, if that's easier.

**Review by ckarwin — APPROVED** [review]
All checks are passing now after restricting matplotlib version. This PR can be merged.

**Pull request merged**
