### PR TITLE
Detector response and other ancillary code

### PR DESCRIPTION
**Pull request by israelmcmc**
The main goal of this branch is to add the class `FullDetectorResponse`, which handles the all-sky instrument response matrix. It can output `DetectorResponse` objects, which correspond to the response to a particular direction. If convolved with an exposure map, it can also return a `PointSourceResponse`, which can be further be convolved with a spectral hypothesis to compute the expected excess counts.

This is explained in the tutorial in `docs/tutorials/DetectorResponse.ipynb`. The API for all classes is also documented, and can be compiled by installing sphinx --e.g. `conda install -c conda-forge sphinx nbsphinx` and `pip install sphinx_rtd_theme`-- and running `make html` in the `docs` folder. 

Other ancillary classes are 
- `SpacecraftFrame`, which registers a new frame with `astropy` to specify local coordinate
- `Attitude`, which specifies the orientation of the SC with respect to an inertial frame --e.g. icrs, galactic. This is explained in `docs/tutorials/UnitsAndCoords.ipynb`. 
- `HealpixAxis`,  a light wrapper which inherits from `histpy` and `mhealpy` in order to handle 2D spherical axes in the detector response. 
- `Configurator`, yet another yaml configurator which makes it easier to override parameters from the command line

For `Configurator`, I added an example in the code for the app `cosi-response`. This is also an example of an entry-point which allows us to use some tools from the command line. For example, once you install this branch, you can run e.g. `cosi-response plot aeff cosipy/test_data/test_full_detector_response.h5 --lat 90deg --lon 0deg` to conveniently inspect the effective area for a detector response. 

`cosipy/test_data/` contains this and other files used for examples and test. `test_full_detector_response.h5` for example is a toy detector response with a very coarse resolution. You can use the files in `test_data` from any script by doing e.g.
```python
import cosipy.test_data
dr_file = cosipy.test_data.path/"test_full_detector_response.h5"
```

I wrote unit tests for most of the code. These are in the `tests` folder. You can install and execute `pytest` in the root folder to run all the tests. Better yet, install `pytest-cov` --e.g. `conda install -c conda-forge pytest-cov`-- and run `pytest --cov=cosipy --cov-report term --cov-report html:tests/coverage_report`. If you then open `tests/coverage_report/index.html ` you can see exactly which lines of codes are tested at least once.

This requires the latest version in the develop branch of `histpy` and `mhealpy`. My latest tests were with these versions:
- `cosipy`: ed6b45a
- `histpy`: 8691f70
- `mhealpy`: 3b16ac7

I decided to stop here but there are other stuff that is needed. I opened some issues for some of this things --e.g. #6 , #8 . We'll should add more as we start to identify those needs. 

Since this is a big PR which contains multiple versions of notebook and binary files, I recommend to do `squash and merge`. This will "flatten" the history and add a single commit to the `main` branch. We should probably do this always anyways since we're using forks.

### CODE REVIEW

**Comment by israelmcmc** [comment]
This is the conda env where I tested this, in case you need to troubleshoot

[conda_env.txt](https://github.com/cositools/cosipy/files/9311923/conda_env.txt)

**Comment by JBeechert** [comment]
After cloning this branch, histpy, and mhealpy, I was able run through the example notebooks successfully. 

@israelmcmc helped me through a few issues along the way, most of them related to version conflicts. I made a new virtual environment with conda and eventually used an environment yaml which he sent me. Python 3.8.1 and nbconvert 6.4.4 worked. My first attempt was with Python 3.7, which gave me nbconvert 5.6.1. That caused `make html` to fail in the `docs` folder.

**Comment by tsiegert** [comment]
**Started with clean python3.8 virtual environment:**
`mkvirtualenv -p python3.8 cosipy`

**Cloned repo:**
`git clone -b DetectorResponse https://github.com/israelmcmc/cosipy.git`

**Tried to install to venv:**
```
cd cosipy
python setup.py install
```
Error: `ModuleNotFoundError: No module named 'Cython'`
```
pip install Cython
python setup.py install
```
Error: `ModuleNotFoundError: No module named 'numpy'`
```
python setup.py install
Finished processing dependencies for cosipy==0.0.1
```

**Getting specific mhealpy and histpy commits:**
```
pip install git+https://gitlab.com/burstcube/mhealpy.git@3b16ac7770153e6fafe80522ad6ef70c599d55c9
pip install git+https://gitlab.com/burstcube/histpy.git@7bf17cdb9330708475c490e9122353cb921d28d8
```

**Doing docs:**
```
pip install sphinx nbsphinx
pip install sphinx_rtd_theme
cd docs
make html
build succeeded, 30 warnings.
The HTML pages are in _build/html.
```


**Trying to use notebooks:**
docs/tutorials/Intro.ipynb:
```
from cosipy import DetectorResponse
dr = DetectorResponse()
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [1], in <cell line: 3>()
      1 from cosipy import DetectorResponse
----> 3 dr = DetectorResponse()

File ~/.virtualenvs/cosipy/lib/python3.8/site-packages/cosipy-0.0.1-py3.8.egg/cosipy/response/DetectorResponse.py:31, in DetectorResponse.__init__(self, *args, **kwargs)
     29 def __init__(self, *args, **kwargs):
---> 31     super().__init__(*args, **kwargs)
     33     self._spec = None
     34     self._aeff = None

TypeError: __init__() missing 1 required positional argument: 'edges'
```

docs/tutorials/DetectorResponse.ipynb:
First:
`FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/Users/thomassiegert/.virtualenvs/cosipy/lib/python3.8/site-packages/cosipy-0.0.1-py3.8.egg/cosipy/test_data/test_full_detector_response.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)`

Changing to absolute path:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [13], in <cell line: 3>()
      1 from cosipy.response import FullDetectorResponse
----> 3 response = FullDetectorResponse.open(response_path)
      5 print(response.filename)
      7 response.close()

File ~/.virtualenvs/cosipy/lib/python3.8/site-packages/cosipy-0.0.1-py3.8.egg/cosipy/response/FullDetectorResponse.py:80, in FullDetectorResponse.open(cls, filename)
     76 axis_type = axis.attrs['TYPE']
     78 if axis_type == 'healpix':
---> 80     axes += [HealpixAxis(edges = np.array(axis),
     81                          nside = axis.attrs['NSIDE'],
     82                          label = axis_label,
     83                          scheme = axis.attrs['SCHEME'],
     84                          coordsys = SpacecraftFrame())]
     86 else:
     87     axes += [Axis(np.array(axis) * u.Unit(axis.attrs['UNIT']),
     88                   scale = axis_type,
     89                   label = axis_label)]

File ~/.virtualenvs/cosipy/lib/python3.8/site-packages/cosipy-0.0.1-py3.8.egg/cosipy/response/healpix_axis.py:19, in HealpixAxis.__init__(self, nside, edges, scheme, coordsys, label, *args, **kwargs)
     11 def __init__(self,
     12              nside,
     13              edges = None,
   (...)
     16              label = None,
     17              *args, **kwargs):
---> 19     HealpixBase.__init__(self,
     20                          nside = nside,
     21                          scheme = scheme,
     22                          coordsys = coordsys)
     24     if edges is None:
     25         # Default to full map
     26         edges = np.arange(self.npix + 1)


TypeError: __init__() got an unexpected keyword argument 'coordsys'
```

docs/tutorials/UnitsAndCoords.ipynb:
Runs without problems.


About the intro and DetectorResponse:
I presume the errors are related to the mhealpy or histpy versions, but the commits you said on slack are installed.

**Comment by tsiegert** [comment]
Running
`cosi-response plot aeff cosipy/test_data/test_full_detector_response.h5 --lat 90deg --lon 0deg`
will also result in
```
Traceback (most recent call last):
  File "/Users/thomassiegert/.virtualenvs/cosipy/bin/cosi-response", line 11, in <module>
    load_entry_point('cosipy==0.0.1', 'console_scripts', 'cosi-response')()
  File "/Users/thomassiegert/.virtualenvs/cosipy/lib/python3.8/site-packages/cosipy-0.0.1-py3.8.egg/cosipy/response/FullDetectorResponse.py", line 335, in cosi_response
    with FullDetectorResponse.open(args.filename) as response:
  File "/Users/thomassiegert/.virtualenvs/cosipy/lib/python3.8/site-packages/cosipy-0.0.1-py3.8.egg/cosipy/response/FullDetectorResponse.py", line 80, in open
    axes += [HealpixAxis(edges = np.array(axis),
  File "/Users/thomassiegert/.virtualenvs/cosipy/lib/python3.8/site-packages/cosipy-0.0.1-py3.8.egg/cosipy/response/healpix_axis.py", line 19, in __init__
    HealpixBase.__init__(self,
TypeError: __init__() got an unexpected keyword argument 'coordsys'
```

**Comment by israelmcmc** [comment]
I was just chatting with @ckarwin who run into the same issue. The problem was that Python was picking up an older version of mhealpy. Chris checked with
```
import mhealpy
print(mhealpy.__path__)
```
And deleted the folder for the older version.

**Comment by israelmcmc** [comment]
Btw, I think this kind of issues should be solved with a proper setup.py once I released new versions of mhealpy and histpy

**Comment by tsiegert** [comment]
> 

```
import mhealpy
print(mhealpy.__path__)
```

`['/Users/thomassiegert/.virtualenvs/cosipy/lib/python3.8/site-packages/mhealpy-0.2.2-py3.8.egg/mhealpy']`

There is just one.
Is there a way to check the specific commit that should be installed?

**Comment by ckarwin** [comment]
To install I did the following:

for healpy:
git clone git@gitlab.com:burstcube/mhealpy.git
cd mhealpy
git checkout 3b16ac7
python setup.py develop

For histpy:
git clone git@gitlab.com:burstcube/histpy.git
cd histpy
git checkout 8691f70
pip install -e .

For cosipy:
git clone --branch DetectorResponse https://github.com/israelmcmc/cosipy.git
cd cosipy
git checkout ed6b45a
pip install -e .

**Comment by ckarwin** [comment]
As Israel said, I had to first remove 2 old version of mhealpy. Now everything seems to be working ok, so far.

**Comment by israelmcmc** [comment]
If you do it like Chris (clone + checkout + pip install -e .) then the `__path__` should point to the folder where you have your working copy of the repo (not the one in the conda env sit-packages). There you can do `git status` to check the commit. If you used "pip + url + commit" then I'm not sure how to check the actual commit (`conda list` or `pip list` I suppose), but I would instead `cd` into `/Users/thomassiegert/.virtualenvs/cosipy/lib/python3.8/site-packages` and check if there are more than one mhealpy folders.

**Comment by tsiegert** [comment]
Yup, after cloning mhealpy and histpy and checking out the commits specifically, it works.

Will run different cases now and check the code later / tomorrow.

Thanks!

**Comment by JBeechert** [comment]
I hadn't tested this before I commented, but for what it's worth, I can run ` cosi-response plot aeff cosipy/test_data/test_full_detector_response.h5 --lat 90deg --lon 0deg` without errors. A plot appears. 

`import mhealpy
print(mhealpy.__path__)` gives
`['/Users/jacqueline/software/mhealpy/mhealpy']
`

My installation went something like this, just copying from my notes:

**Made a virtual environment with Israel's environment.yml**
`conda env create -f environment.yml`
Creates 'cosi' environment (do `conda activate cosi` to activate it)

On my mac, 
**cosipy**
```
mkdir ~/software
cd /Users/jacqueline/software
git clone --branch DetectorResponse git@github.com:israelmcmc/cosipy.git
cd cosipy
pip install -e .
```

**histpy**
```
cd ~/software
git clone git@gitlab.com:burstcube/histpy.git
cd histpy
git checkout develop
pip install -e .
```

**mhealpy**
```
cd ~/software
git clone git@gitlab.com:burstcube/mhealpy.git
cd  mhealpy
git checkout develop
pip install -e .
```

**docs**
```
cd docs
make html
```
Got an error saying pandoc wasn't installed --> `brew install pandoc` 
`make html`
No errors.

**Comment by ckarwin** [comment]
I successfully went through the response tutorial and have been looking through the full PR. Very nice work @israelmcmc! Here are some notes:

I am using Clemson's palmetto cluster, and I installed in the same MEGAlib environment that I've been using for the data challenges (it's a conda environment). After fixing the issue with my local mhealpy versions (see above comments), everything worked ok. To run the tutorial I copied all the commands to a normal python script and ran from the command line. I was able to reproduce all the outputs. I also successfully tested the command line options with the Configurator. 

The only thing I didn't test is 'make html' in 'docs'. I was a bit worried about the dependencies:
conda install -c conda-forge sphinx nbsphinx
conda takes a long time to solve the environment because of some conflicts with my root dependencies. Ultimately, it solves the environment, but it wants to make a bunch of package updates/downgrades to make the install. I didn't want to break anything with my working MEGAlib, so I didn't go forward with the install. This might not cause any problems, and I can test more later. But I'm curious, is there a way to include the API documentation without needing to compile it? Or what is the reasoning for setting the documentation up in this way?

I still need to play around with the new response class some more, but so far I haven't found any major issues.

**Comment by israelmcmc** [comment]
Thanks @ckarwin!

You can always access the API documentation using Python's builtin `help()` function. Using sphinx and Jupyter tutorials is just a way to make it nicer to browse. Ultimately very few users will need to compile the documentation. Typically it is compiled automatically as part of the continuous integration pipeline in GitHub and by the ReadTheDocs runners. These are the ones we need to setup up.

**Comment by ckarwin** [comment]
I ran the unit tests with no problem:

pip install pytest
pip install pytest-cov

from the root directory (i.e. cosipy) I ran:
pytest --cov=cosipy --cov-report term --cov-report html:tests/coverage_report
13 tests are performed and all pass. 
I get a total coverage of 89%

To view the report in index.html I did (although it prints out to the command line as well):
python
import webbrowser
webbrowser.open("index.html")
@israelmcmc Is this the best way to view the .html file?

**Comment by tsiegert** [comment]
I tested the following to compare the full response at a pixel to the interpolated one:

```
from cosipy import test_data
import matplotlib.pyplot as plt
import numpy as np
from astropy.coordinates import SkyCoord
from cosipy.coordinates import SpacecraftFrame
import astropy.units as u

response_path = test_data.path / "test_full_detector_response.h5"

response = FullDetectorResponse.open(response_path)

print(response.axes.labels)
print(response.axes.nbins)
print(response.pix2skycoord(np.arange(12)))

sky_pixel = 4
lon_offset = 0.00*u.deg
lat_offset = 0.00*u.deg

lon = response.pix2skycoord(sky_pixel).lon
lat = response.pix2skycoord(sky_pixel).lat


drm2 = response[sky_pixel]
drm1 = response.get_interp_response(SkyCoord(lon+lon_offset,
                                             lat+lat_offset,
                                             frame=SpacecraftFrame))

cds1 = drm1.project(['Phi','PsiChi'])
cds2 = drm2.project(['Phi','PsiChi'])

diff = (cds1[:].todense()-cds2[:].todense())/cds1[:].todense()*100

fig, axes = plt.subplots(nrows=1,ncols=3,figsize=(16,5))
cds1.plot(ax=axes[0])
cds2.plot(ax=axes[1])
pp = axes[2].pcolormesh(cds1.axes[0].edges.value,
                        cds1.axes[1].edges,
                        diff.T)
axes[2].set_xlabel(cds1.axes[0].label)
axes[2].set_ylabel(cds1.axes[1].label)
fig.colorbar(pp,label='relative difference %')

for ax in axes:
    ax.set_xlim(0,90)

plt.tight_layout()

```

We might want to implemented that or a similar thing as a unit test.

**Comment by tsiegert** [comment]
Also question @israelmcmc
Is there a way in histpy to drop an axis? I can manage to either rebin the last to axes or slice the 0th entries, but this doesn't change the entire object. Starting from an HDF5 file to read in the response, we might want to completely drop axes if not done in a previous step. I thinking of the sigma/tau and distance dimension of which the first will not be realised in COSI and the second will be like a switch instead of a part of a response. What do you think?

**Comment by israelmcmtest** [comment]
@ckarwin @tsiegert Thanks for running the tests and checking the code

> To view the report in index.html I did (although it prints out to the command line as well): python import webbrowser webbrowser.open("index.html") @israelmcmc Is this the best way to view the .html file?

You can open it in any web browser as a regular webpage.

> We might want to implemented that or a similar thing as a unit test.

Makes sense. We could use approx() or a similar function to account for a potential floating point error

> Is there a way in histpy to drop an axis?

Yes, use project() and exclude the axis you want to drop from the list. I don’t remember if I added the flag to invert which axes are projected, or of I only thought about it (just to make it easier on the user)

**Comment by ckarwin** [comment]
We have discussed this PR with the COSIpy WG and all agree that it is ready to be merged.

**Pull request merged**
