### PR TITLE
how to deal with gaussian normalisation

### PR DESCRIPTION
**Pull request by GallegoSav**
minor changes : 

- now we can read response file with gaussian spectrum
- if there is only one bin the normalization is treat as same as the Mono one
- Check if there is one bin and if the gaussian spectrum is fully contained in that bin
- Raise a NotImplementedError if there are more than one bin with gaussian spectrum

### CODE REVIEW

**Comment by israelmcmc** [comment]
Thanks, @GallegoSav . I haven't had time to run it yet, but I checked the code and the logic looks good to me.

**Comment by israelmcmc** [comment]
@GallegoSav sorry I kept forgetting to check this! Do you think we need to merge this before DC2? I don't think so, and I'd rather merge as little code as possible right before the release, but please let me know if you think we do need it. Otherwise, I'll come back to this after the release.

**Comment by israelmcmc** [comment]
I changed the target branch to "develop". I want to avoid adding new features to the version we're releasing today. I'll explain this further tomorrow during the cosipy meeting.

**Comment by GallegoSav** [comment]
> I changed the target branch to "develop". I want to avoid adding new features to the version we're releasing today. I'll explain this further tomorrow during the cosipy meeting.

Yeah no problem, indeed I don't think it is necessary for DC2 as there no source with gaussian spectrum so far I suppose

**Comment by israelmcmc** [comment]
@GallegoSav I opened a [PR](https://github.com/GallegoSav/cosipy/pull/1) into your branch for this PR with some changes:
- I synced to the current develop branch and fixed some conflicts
- When you check it this is a single-bin response, I added a check that the normalization is Gaussian (other types or normalizations can also be single bin).

Please review it and when you incorporate those changes this PR can be merged. I think the coverage test will not pass, but I'll bypass it since this is a "heritage" PR, since before the unit tests were implemented. 

Thanks for working on this and sorry it took so long to review!

**Comment by GallegoSav** [comment]
@israelmcmc I merged your pull request ( I think I could also just synchronized my fork to be up-to-date) . You can now merge this pull request

**Comment by israelmcmc** [comment]
Thanks, @GallegoSav. I'm merging this.

**Pull request merged**
