### PR TITLE
Initial setup

### PR DESCRIPTION
**Pull request by israelmcmc**
This is the boilerplate setup to install cosipy with pip (and setuptools), as well as and example on how to deal with classes, scripts and executables. 

This will allows us to push to PiPy, and then do `pip install cosipy` for the releases. For now however, and in general for developers, the way to install it is as follows (preferably inside a conda env):
```
git clone git@github.com:cositools/cosipy.git
cd cosipy
pip install -e .
```

The `setup.py` script has an "entry point". This is an automatic executable that is created during the installation. You can run in the terminal or a bash script
```
$ cosi-rsp-dump /path/to/file
Filename: /path/to/file. No contents for now!
```

or get help:
```
$ cosi-rsp-dump -h
usage: cosi-rsp-dump filename [--help] [options]

Dump DR contents

positional arguments:
  filename    Path to instrument response

optional arguments:
  -h, --help  show this help message and exit
```

In a python script, you can do instead:
```
>>> from cosipy.response import DetectorResponse
>>> dr = DetectorResponse("/path/to/file")
>>> dr.dump()
Filename: /path/to/file. No contents for now!
```

And finally, the advantage of entry points is that you can test them as any other method with e.g.
```
>>> from cosipy.response import cosi_rsp_dump 
>>> cosi_rsp_dump(['/path/to/file'])
Filename: /path/to/file. No contents for now!
```

### CODE REVIEW

**Comment by zoglauer** [comment]
Hi Israel,

Great start!

Although DetectorResponse.py is just an example, could you do the proper source code documentation? I want us to start with this right from the beginning.

Some of your description in the commit message should go into the documentation.

The cosi-setup tools set up a full environment and already clone/update cosipy. Thus I just have to add in the setup-stage2.py:
cd cosipy
pip install -e .
To have it accessible in the environment?

**Comment by ckarwin** [comment]
Hi Israel, 

I tested your PR as follows:

1. Made a conda environment with python=3.9 on Clemson's palmetto cluster 
2. git clone --branch init_setup https://github.com/israelmcmc/cosipy.git
3. cd cosipy
4. pip install -e .

I then reproduced all the output that you have in your commit message -- everything worked fine. 

A few questions:

What are the primary purposes of the entry points? I guess in general the setup script will include multiple entry points?
Are they just for testing? Should the same be done for all classes? It seems that this can also be used to define command line tools?

Is the cosi_rsp_dump just meant to be a dummy example or should a similar structure be included in all the classes?

In general, for testing the code, can you clarify exactly what this should entail? And what are the best practices for writing the code with necessary tests? Maybe this is something that we can also discuss at our next meeting.

**Comment by zoglauer** [comment]
Hi Israel,

One more request: 
Can you please add a "Requirements.txt" file, so that we can automatically install all required packages into the python environment.

Thanks,
Andreas

**Comment by israelmcmc** [comment]
@zoglauer 

> Although DetectorResponse.py is just an example, could you do the proper source code documentation? I want us to start with this right from the beginning.

Agree, I added the docstrings.

> Some of your description in the commit message should go into the documentation.

I added the boilerplate for the sphinx documentation. In there I included the installation steps, which I think it is what you meant.

> The cosi-setup tools set up a full environment and already clone/update cosipy. Thus I just have to add in the setup-stage2.py:
> cd cosipy
> pip install -e .
> To have it accessible in the environment?

Yes, this is correct. Eventually will want to install a release with `pip install cosipy`, but for now that's it.
 
> Can you please add a "Requirements.txt" file, so that we can automatically install all required packages into the python environment.

That already part of the `setup.py` file (see `install_requires`). When you install it with pip, it'll automatically install those packages.

**Comment by israelmcmc** [comment]
@ckarwin 

> What are the primary purposes of the entry points? 

"entry_points" = command-line executables. It's just the way `setuptools` create them automatically (as opposed to creating a separate file manually).  

> I guess in general the setup script will include multiple entry points?

Yes, the setup script will have multiple entry points, one per executable.

>  Are they just for testing? 

Yes, kinda. Having the command-line tools as functions, and creating the executables automatically using entrypoint, allows you to test them with pytest the same as any other function.

> Should the same be done for all classes? 

Not all classes will need this. 

> It seems that this can also be used to define command line tools?

Yes

> Is the cosi_rsp_dump just meant to be a dummy example or should a similar structure be included in all the classes?

It is a dummy example for now, but I've found it useful for other experiment. I guess I'll keep it and make it do something for real.

> In general, for testing the code, can you clarify exactly what this should entail? And what are the best practices for writing the code with necessary tests? Maybe this is something that we can also discuss at our next meeting.

I added the folder `test` with an example. There's also a testing section in the docs. 

> Why is __init__.py in cosipy empty? What will this contain?

An empty `__init__.py` files indicates to Python that the folder is a module. The contents are executed the first time a module is imported. It's no longer empty now though, so you can see an example.

**Pull request merged**
