### PR TITLE
Update preliminary TS map

### PR DESCRIPTION
**Pull request by PbU-Jason**
Hi, I'm Jason.
I reviewed my previous code on implementing multi-resolution TS map using HealpixMap.
My notebook and explanatory PDF file have been put to cosipy/cosipy/ts_map/preliminary/.
I was hoping that my pull request would not affect the main branch. However, I can not create a branch on cositools/cosipy/.
Therefore, I'm pulling my local branch directly to the main branch of cositools/cosipy/.
Please let me know if anything is wrong. Thanks a lot!

### CODE REVIEW

**Comment by israelmcmc** [comment]
Tagging @Yong2Sheng. Hopefully this could be merged with the current code.

**Comment by Yong2Sheng** [comment]
Thank you very much @PbU-Jason and @israelmcmc, I will also take a look at this.

**Comment by israelmcmc** [comment]
I changed the target branch to "develop". I want to avoid adding new features to the version we're releasing today. I'll explain this further tomorrow during the cosipy meeting.

**Comment by israelmcmc** [comment]
I'm closing this in favor of #248, since it's based on the same code. Thank you, @PbU-Jason!

**Pull request closed without merging**
