### PR TITLE
Update yaml files

### PR DESCRIPTION
**Pull request by eneights**
Add 'ori_file' to yaml files to be compatible with DataIO update

### CODE REVIEW

**Review by ckarwin — COMMENTED** [review]
Thanks @eneights. Can you just remove your paths in data_file and ori_file?

**Comment by eneights** [comment]
@ckarwin done!

**Comment by ckarwin** [comment]
Sorry, Eliza, but can you put a dummy file bane there: 'input_file' ?
A null string might be bit confusing.

**Review by ckarwin — APPROVED** [review]
Thanks again, Eliza. The PR can be merged now.

**Pull request merged**
